#!/usr/bin/env bash

LocalRepo="$1"
ApiKey="$2"


if [ "$LocalRepo" == "" ]; then
    #LocalRepo="/Users/ali/Projects/MateMachine/LocalNuget/"
    LocalRepo="E:\\LocalNuget"
fi
# if [ "$ApiKey" == "" ]; then
#     ApiKey="secret"
# fi


cecho(){
  RED="\033[0;31m"
  GREEN="\033[0;32m"  # <-- [0 means not bold
  YELLOW="\033[1;33m" # <-- [1 means bold
  CYAN="\033[1;36m"
  # ... Add more colors if you like

  NC="\033[0m" # No Color

  # printf "${(P)1}${2} ${NC}\n" # <-- zsh
  printf "${!1}${2} ${NC}\n" # <-- bash
}

push() {
  cecho "CYAN" "Pushing $1..."

  # dotnet nuget push "$1" --source "$LocalRepo" --api-key "$ApiKey"
  nuget push -source "$LocalRepo" "$1" -ApiKey "$ApiKey"

  if [ $? -eq 0 ]; then
    cecho "GREEN" "$1 was pushed successfully"
    echo
    echo
  else
    cecho "RED" "An error in pushing $1"
    exit 1;
  fi
}


cecho "CYAN" "Building packages..."

find . -name "*.nupkg" -type f -delete &>/dev/null

dotnet build MateMachine.Extensions.sln
dotnet pack --include-symbols MateMachine.Extensions.sln

echo
echo
cecho "GREEN" "Building packages were successful."
echo
echo

cecho "CYAN" "Pusing packages to $LocalRepo"

shopt -s nullglob
for i in `find . -name "*.nupkg" -type f`; do
  push "$i"
done
