kind: pipeline
type: docker
name: default

steps:
- name: deploy services
  image: docker/compose
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  environment:
    DOCKER_BUILDKIT: 1
    DOCKER_REGISTRY: { from_secret: "DOCKER_REGISTRY"}
    DOCKER_USER: { from_secret: "DOCKER_USER" }
    DOCKER_PASSWORD: { from_secret: "DOCKER_PASSWORD" }
  commands:
  - echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin
  - docker-compose -p $DRONE_REPO_NAME -f docker-compose.yml -f docker-compose.build.yml build
  - docker tag $DRONE_REPO_NAME:latest "$DOCKER_REGISTRY/$DRONE_REPO_OWNER/$DRONE_REPO_NAME:latest"
  - docker push "$DOCKER_REGISTRY/$DRONE_REPO_OWNER/$DRONE_REPO_NAME:latest"
  - docker-compose -p $DRONE_REPO_NAME -f docker-compose.yml up -d --remove-orphans
  when:
    branch: main

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
